### ISSUE TITLE
Crashing due to package move

### ISSUE THREAD

**Issue by Darkere** [klikli-dev/occultism-kubejs#1]
https://github.com/klikli-dev/occultism/commit/c8a2c286cccf5b1c3245afcafa89e33a274db46a

https://gnomebot.dev/paste/1136009437388230807

**Comment by klikli-dev** [comment]
mea culpa - will fix!

**Comment by klikli-dev** [comment]
Fixed in f08b73b0688ddd197800606ff5e7697950867bad
