### ISSUE TITLE
Example crushing Code does not work, even changing tags.

### ISSUE THREAD

**Issue by desagas** [klikli-dev/occultism-kubejs#5]
Maybe I am a very new KubeJS user, but your server example code clearly shows the following, and it simply does not work.

```
event.recipes.occultism.crushing(
		'2x #forge:ores/iron',
		'#forge:tools/swords'
	)
```

I even tried changing, for neoforge, to`'#c:ores/iron', '#minecraft:swords'`. I also tried `'minecraft:iron_ore', '#minecraft:swords'`, `'minecraft:iron_ore', 'minecraft:iron_sword'`, but, no amount of changing ingredients and tags let me add any crushing recipe at all to the game.

I believe this is a bug, mainly because even your example code does not work. Perhaps it is registering ingredients or tags differently in neoforge? Spirit fire works just fine, but crushing does not. `event.recipes.occultism.crushing('6x minecraft:emerald_ore', 'minecraft:iron_sword'` does absolutely nothing but error: `unable to cast 'result:occultism:recipe_result' value '6x minecraft:emerald_ore' to 'occultism:recipe_result'!`. Again, regardless of what set of tags or ingredients I put in, nothing works.

OKjs Version: is 1.21.1-neoforge-1.2.1.
Occultism Version: 1.21.1-neoforge-1.154.0
Neoforge Version: .34

**Comment by klikli-dev** [comment]
@desagas thanks for reporting, where is that example from?

It's 1.20.1 code instead of 1.21.1 so I probably missed updating documentation somewhere.

The actual code running if you check out this repo is this: https://github.com/klikli-dev/occultism-kubejs/blob/version/1.21.1/runs/client/kubejs/server_scripts/example.js

**Comment by desagas** [comment]
Hi, it was the user code/run/client/kubejs/server_scripts/example on this GitHub. Or, at least I thought it was? Or perhaps I was viewing a previous git version somehow? Either way, I see the up to date code now.

I’ll check that out. Sorry for wasting an issue. Thank you so much!

**Comment by klikli-dev** [comment]
I suspect you somehow got the link to an old version, because the code you posted was correct in older minecraft and kubejs versions!

No worries, I will close this issue, if any problems pop up you can open a new one :)

**Comment by desagas** [comment]
Sorry to continue this, but, I am having a lot of trouble putting in Entities for sacrifice in rituals. I have tried the way Occultism does, in their recipe builder, but that does not work. I have tried just putting in `"cows"` or `"cow"` or `"#minecraft:cow"` or `"minecraft:cow"` or `"Entity.Cow,"` but after trying for a couple of hours, I can not find a single example of a custom ritual using an sacrifice.

My current code is described below, but I can not get the entity to properly work for this, KubeJs keeps telling me "can not convert to string or tag," when referring to the entityToSacrifice

```
    event.recipes.occultism.ritual(
        'minecraft:iron_ore',
        [
            "#c:raw_materials/iron",
            "#c:raw_materials/iron"
        ],
        '#c:stones',
        'occultism:summon_marid'
    ).dummy("kubejs:ritual_ore_creator").entityToSacrifice("#minecraft:cows")
```

I appreciate any help.

**Comment by desagas** [comment]
Strangely enough, the mod itself does not have the unbound afrit implemented, where one would typically sacrifice a cow. Maybe it is an occultism itself bug, or something? I am not too sure.

**Comment by klikli-dev** [comment]
@desagas I just tested this and I think we are running into an issue with kubejs that the Enigmatica devs also encountered: https://github.com/EnigmaticaModpacks/Enigmatica10/issues/90

Basically if an entity to sacrifice is present, somehow kubejs removes the recipe. I am not sure yet why, I did post this on the kubejs dsicord to figure otu more

**Comment by klikli-dev** [comment]
@desagas I may just have fixed that Enigmatica issue .. but either way, I now included a sample on how to properly use the entity to sacrifice. 

To use that, please update to latest occultism kubejs (1.3.0, now building), as I had to customize something that kube usually does automatically, simply because I do not know how to use it with the kube automatic stuff

**Comment by desagas** [comment]
The startup example code errors when booting up: 
[startup.log](https://github.com/user-attachments/files/16852889/startup.log)

I updated to 1.4.0, should I revert to 1.3.0?

**Comment by klikli-dev** [comment]
> The startup example code errors when booting up: [startup.log](https://github.com/user-attachments/files/16852889/startup.log)
> 
> I updated to 1.4.0, should I revert to 1.3.0?

1.4.0 uses latest kubejs dev (which has a breaking change apparently, I had to change the code I used in 1.3.0)
1.3.0 should work on the version you currently have, and 1.4.0 does not add any new features, they are already in 1.3.0, so that should be the way to go

**Comment by desagas** [comment]
Not to push more of this, but, because KubeJS has updated, other mods needed to update, and this mod is not compatible with the latest KubeJS in my pack. This time, it is not just a recipe error, even with blank files, it does not make it past startup. Perhaps there is another problem, but, I will post my logs as I did before for you.

Let me know if I need to create a separate issue for you.

I get three errors from JubeJS Startup: something about the dummy item not being registered properly, or something like that.

One thing to note is that sometimes an error with Theurgy KubeJS causes the Occultism KubeJS to error or warn, so, I am unsure which mod is causing which issue.

Latest KubeJS startup log:
[startup.log](https://github.com/user-attachments/files/16922741/startup.log)

Latest Log: 
[latest.log](https://github.com/user-attachments/files/16922748/latest.log)

Latest Debug Log: 
[debug.log](https://github.com/user-attachments/files/16922749/debug.log)
