### ISSUE TITLE
Rituals stop working

### ISSUE THREAD

**Issue by Wopura** [klikli-dev/occultism-kubejs#6]
**Describe the bug**
A large portion of the rituals are bugged and do not work or show up in the book or JEI.

**To Reproduce**
1. Open Dictionary of Spirits/JEI
2. Check the recipe for certain rituals
3. Not there

**Expected behavior**
Recipes are visible and work.

**Screenshots**
![image](https://github.com/user-attachments/assets/607e8b57-1355-45e6-9b92-750016f3ac13)
![image](https://github.com/user-attachments/assets/41dc867d-f033-4cab-8390-a00a8e2a9686)

**System (please complete the following information):**
- Occultism KubeJS Version: 1.1.0
- OS: Windows 10
- Minecraft Version: NeoForge 1.21
- Modpack Link and Version, or list of mods: Adorned API, AE2 Wireless Terminals, Amendments, Apothic Attributes, Apothic Enchantments, Apothic Spawners, AppleSkin, Applied Energistics 2, Applied Mekanistics, Architectury, Ars Additions, Ars Elemental, Ars Nouveau, Ars Ocultas, Balm, Cloth Config, Comforts, CraterLib, Easy Piglins, Easy Villagers, OpenBlocks Elevator Port, Farmer's Delight, Farming for Blockheads, FastWorkbench, FerriteCore, Framework, GeckoLib, Industrial Foregoing, Jade, Just Enough Items, KubeJS, Measurements, Mekanism + Mekanism: Generators, ModernFix, Modonomicon, MoonlightLib, Mouse Tweaks, MrCrayfish's Furniture Mod, Nature's Compass, Occultism, Patchouli, Placebo, Polymorph, Polymorphic Energistics, Productive Bees, Rhino, Simple RPC, Sky Void Additions, SmartBrainLib, Sophisticated Backpacks/Storage/Core, Squat Grow, Titanium, Xaero's Minimap and World Map

**Additional Context**
This issue stops when I remove Occultism KubeJS. I have modified recipes, but removing those modifications does not fix the issue.

**Comment by klikli-dev** [comment]
@Wopura please make sure to use latest occultism + latest kubejs.
The kubejs version you are using is quite outdated, if both mods are up to date it *should* work, at least I know of a few bigger packs that use it and it works. If issues remain please ping me here to reopen, or start a new issue.
