### ISSUE TITLE
Crash when trying to make a world with the Pentacle Rework Update

### ISSUE THREAD

**Issue by micrwvae** [klikli-dev/occultism-kubejs#7]
**Describe the bug**
Game crashes when trying to create a world

**To Reproduce**
1.install occultism and occultism-kube as well as dependencies
2.create a world 

Expected behavior**

**Screenshots**

**System (please complete the following information):**
- Occultism KubeJS Version:  1.7.0
- OS: Windows 10
- Minecraft Version: 1.21.1
- Modpack Link and Version, or list of mods: 
![image](https://github.com/user-attachments/assets/c2babcbf-e532-4f66-961c-0a0ec034f605)

**Additional context**
https://mclo.gs/pLE2G2U

**Comment by klikli-dev** [comment]
Closed in b481cd14db467427808055f422446866306ec6b8
